//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClarityServicesTestUnits.LVFWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedorVadorRequest", Namespace="http://schemas.datacontract.org/2004/07/ClarityServices.LedorVador")]
    [System.SerializableAttribute()]
    public partial class LedorVadorRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClarityServicesTestUnits.LVFWS.LedorVadorFlowPackage> packagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClarityServicesTestUnits.LVFWS.LedorVadorFlowPackage> packages {
            get {
                return this.packagesField;
            }
            set {
                if ((object.ReferenceEquals(this.packagesField, value) != true)) {
                    this.packagesField = value;
                    this.RaisePropertyChanged("packages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedorVadorFlowPackage", Namespace="http://schemas.datacontract.org/2004/07/ClarityServices.LedorVador")]
    [System.SerializableAttribute()]
    public partial class LedorVadorFlowPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documento_externIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documento_numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empresaPropiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string establecimiento_numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int histClinicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double importeUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoImpuestoId_IvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoServicioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento_externId {
            get {
                return this.documento_externIdField;
            }
            set {
                if ((object.ReferenceEquals(this.documento_externIdField, value) != true)) {
                    this.documento_externIdField = value;
                    this.RaisePropertyChanged("documento_externId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento_numero {
            get {
                return this.documento_numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.documento_numeroField, value) != true)) {
                    this.documento_numeroField = value;
                    this.RaisePropertyChanged("documento_numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empresaPropia {
            get {
                return this.empresaPropiaField;
            }
            set {
                if ((this.empresaPropiaField.Equals(value) != true)) {
                    this.empresaPropiaField = value;
                    this.RaisePropertyChanged("empresaPropia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string establecimiento_numero {
            get {
                return this.establecimiento_numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.establecimiento_numeroField, value) != true)) {
                    this.establecimiento_numeroField = value;
                    this.RaisePropertyChanged("establecimiento_numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int histClinica {
            get {
                return this.histClinicaField;
            }
            set {
                if ((this.histClinicaField.Equals(value) != true)) {
                    this.histClinicaField = value;
                    this.RaisePropertyChanged("histClinica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double importeUnitario {
            get {
                return this.importeUnitarioField;
            }
            set {
                if ((this.importeUnitarioField.Equals(value) != true)) {
                    this.importeUnitarioField = value;
                    this.RaisePropertyChanged("importeUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipoImpuestoId_Iva {
            get {
                return this.tipoImpuestoId_IvaField;
            }
            set {
                if ((this.tipoImpuestoId_IvaField.Equals(value) != true)) {
                    this.tipoImpuestoId_IvaField = value;
                    this.RaisePropertyChanged("tipoImpuestoId_Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipoServicioId {
            get {
                return this.tipoServicioIdField;
            }
            set {
                if ((this.tipoServicioIdField.Equals(value) != true)) {
                    this.tipoServicioIdField = value;
                    this.RaisePropertyChanged("tipoServicioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedorVadorResponse", Namespace="http://schemas.datacontract.org/2004/07/ClarityServices.LedorVador")]
    [System.SerializableAttribute()]
    public partial class LedorVadorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> documentosAceptadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> documentosOmitidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> documentosAceptados {
            get {
                return this.documentosAceptadosField;
            }
            set {
                if ((object.ReferenceEquals(this.documentosAceptadosField, value) != true)) {
                    this.documentosAceptadosField = value;
                    this.RaisePropertyChanged("documentosAceptados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> documentosOmitidos {
            get {
                return this.documentosOmitidosField;
            }
            set {
                if ((object.ReferenceEquals(this.documentosOmitidosField, value) != true)) {
                    this.documentosOmitidosField = value;
                    this.RaisePropertyChanged("documentosOmitidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LVFWS.ILedorVadorFlowService")]
    public interface ILedorVadorFlowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedorVadorFlowService/SendPackages", ReplyAction="http://tempuri.org/ILedorVadorFlowService/SendPackagesResponse")]
        ClarityServicesTestUnits.LVFWS.LedorVadorResponse SendPackages(ClarityServicesTestUnits.LVFWS.LedorVadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedorVadorFlowService/SendPackages", ReplyAction="http://tempuri.org/ILedorVadorFlowService/SendPackagesResponse")]
        System.Threading.Tasks.Task<ClarityServicesTestUnits.LVFWS.LedorVadorResponse> SendPackagesAsync(ClarityServicesTestUnits.LVFWS.LedorVadorRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILedorVadorFlowServiceChannel : ClarityServicesTestUnits.LVFWS.ILedorVadorFlowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LedorVadorFlowServiceClient : System.ServiceModel.ClientBase<ClarityServicesTestUnits.LVFWS.ILedorVadorFlowService>, ClarityServicesTestUnits.LVFWS.ILedorVadorFlowService {
        
        public LedorVadorFlowServiceClient() {
        }
        
        public LedorVadorFlowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LedorVadorFlowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LedorVadorFlowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LedorVadorFlowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClarityServicesTestUnits.LVFWS.LedorVadorResponse SendPackages(ClarityServicesTestUnits.LVFWS.LedorVadorRequest request) {
            return base.Channel.SendPackages(request);
        }
        
        public System.Threading.Tasks.Task<ClarityServicesTestUnits.LVFWS.LedorVadorResponse> SendPackagesAsync(ClarityServicesTestUnits.LVFWS.LedorVadorRequest request) {
            return base.Channel.SendPackagesAsync(request);
        }
    }
}
