//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClarityServicesTestUnits.LVASMX_SMG01 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedorVadorRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LedorVadorRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClarityServicesTestUnits.LVASMX_SMG01.LedorVadorFlowPackage[] packagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClarityServicesTestUnits.LVASMX_SMG01.LedorVadorFlowPackage[] packages {
            get {
                return this.packagesField;
            }
            set {
                if ((object.ReferenceEquals(this.packagesField, value) != true)) {
                    this.packagesField = value;
                    this.RaisePropertyChanged("packages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedorVadorFlowPackage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LedorVadorFlowPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int histClinicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        private int empresaPropiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documento_externIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string establecimiento_numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documento_numeroField;
        
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        private int tipoServicioIdField;
        
        private int tipoImpuestoId_IvaField;
        
        private double cantidadField;
        
        private double importeUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int histClinica {
            get {
                return this.histClinicaField;
            }
            set {
                if ((this.histClinicaField.Equals(value) != true)) {
                    this.histClinicaField = value;
                    this.RaisePropertyChanged("histClinica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int empresaPropia {
            get {
                return this.empresaPropiaField;
            }
            set {
                if ((this.empresaPropiaField.Equals(value) != true)) {
                    this.empresaPropiaField = value;
                    this.RaisePropertyChanged("empresaPropia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documento_externId {
            get {
                return this.documento_externIdField;
            }
            set {
                if ((object.ReferenceEquals(this.documento_externIdField, value) != true)) {
                    this.documento_externIdField = value;
                    this.RaisePropertyChanged("documento_externId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string establecimiento_numero {
            get {
                return this.establecimiento_numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.establecimiento_numeroField, value) != true)) {
                    this.establecimiento_numeroField = value;
                    this.RaisePropertyChanged("establecimiento_numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string documento_numero {
            get {
                return this.documento_numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.documento_numeroField, value) != true)) {
                    this.documento_numeroField = value;
                    this.RaisePropertyChanged("documento_numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int tipoServicioId {
            get {
                return this.tipoServicioIdField;
            }
            set {
                if ((this.tipoServicioIdField.Equals(value) != true)) {
                    this.tipoServicioIdField = value;
                    this.RaisePropertyChanged("tipoServicioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int tipoImpuestoId_Iva {
            get {
                return this.tipoImpuestoId_IvaField;
            }
            set {
                if ((this.tipoImpuestoId_IvaField.Equals(value) != true)) {
                    this.tipoImpuestoId_IvaField = value;
                    this.RaisePropertyChanged("tipoImpuestoId_Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double importeUnitario {
            get {
                return this.importeUnitarioField;
            }
            set {
                if ((this.importeUnitarioField.Equals(value) != true)) {
                    this.importeUnitarioField = value;
                    this.RaisePropertyChanged("importeUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LedorVadorResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LedorVadorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClarityServicesTestUnits.LVASMX_SMG01.ArrayOfInt documentosAceptadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClarityServicesTestUnits.LVASMX_SMG01.ArrayOfInt documentosOmitidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ClarityServicesTestUnits.LVASMX_SMG01.ArrayOfInt documentosAceptados {
            get {
                return this.documentosAceptadosField;
            }
            set {
                if ((object.ReferenceEquals(this.documentosAceptadosField, value) != true)) {
                    this.documentosAceptadosField = value;
                    this.RaisePropertyChanged("documentosAceptados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ClarityServicesTestUnits.LVASMX_SMG01.ArrayOfInt documentosOmitidos {
            get {
                return this.documentosOmitidosField;
            }
            set {
                if ((object.ReferenceEquals(this.documentosOmitidosField, value) != true)) {
                    this.documentosOmitidosField = value;
                    this.RaisePropertyChanged("documentosOmitidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LVASMX_SMG01.LVServiceSoap")]
    public interface LVServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPackages", ReplyAction="*")]
        ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesResponse SendPackages(ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPackages", ReplyAction="*")]
        System.Threading.Tasks.Task<ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesResponse> SendPackagesAsync(ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPackagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPackages", Namespace="http://tempuri.org/", Order=0)]
        public ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesRequestBody Body;
        
        public SendPackagesRequest() {
        }
        
        public SendPackagesRequest(ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPackagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClarityServicesTestUnits.LVASMX_SMG01.LedorVadorRequest request;
        
        public SendPackagesRequestBody() {
        }
        
        public SendPackagesRequestBody(ClarityServicesTestUnits.LVASMX_SMG01.LedorVadorRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPackagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPackagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesResponseBody Body;
        
        public SendPackagesResponse() {
        }
        
        public SendPackagesResponse(ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPackagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClarityServicesTestUnits.LVASMX_SMG01.LedorVadorResponse SendPackagesResult;
        
        public SendPackagesResponseBody() {
        }
        
        public SendPackagesResponseBody(ClarityServicesTestUnits.LVASMX_SMG01.LedorVadorResponse SendPackagesResult) {
            this.SendPackagesResult = SendPackagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LVServiceSoapChannel : ClarityServicesTestUnits.LVASMX_SMG01.LVServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LVServiceSoapClient : System.ServiceModel.ClientBase<ClarityServicesTestUnits.LVASMX_SMG01.LVServiceSoap>, ClarityServicesTestUnits.LVASMX_SMG01.LVServiceSoap {
        
        public LVServiceSoapClient() {
        }
        
        public LVServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LVServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LVServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LVServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesResponse SendPackages(ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesRequest request) {
            return base.Channel.SendPackages(request);
        }
        
        public System.Threading.Tasks.Task<ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesResponse> SendPackagesAsync(ClarityServicesTestUnits.LVASMX_SMG01.SendPackagesRequest request) {
            return base.Channel.SendPackagesAsync(request);
        }
    }
}
